name: Publish to Maven Central

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  publish:
    name: Publish plugin to Maven Central
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE  }}

      - name: Set up GPG key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import
          echo "allow-loopback-pinentry" >> ~/.gnupg/gpg-agent.conf
          echo RELOADAGENT | gpg-connect-agent
          echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf

      - name: Publish to Sonatype
        run: ./gradlew publish -Psigning.password="${{ secrets.GPG_PASSPHRASE }}" -PossrhUsername=${{ secrets.OSSRH_USERNAME }} -PossrhPassword=${{ secrets.OSSRH_PASSWORD }}
