name: Publish to Maven Central

on:
  workflow_dispatch:
    inputs:
      RELEASE_VERSION:
        type: string
        description: Release Version
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  publish:
    name: Publish plugin to Maven Central
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup release version
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "RELEASE_VERSION=${{ github.event.inputs.RELEASE_VERSION }}" >> $GITHUB_ENV
          else
            echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          fi

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE  }}

      - name: Build
        run: ./gradlew clean fatJar

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          name: keycloak_phone_validation-${{ env.RELEASE_VERSION }}.jar
          tag_name: ${{ github.ref }}
          files: build/libs/*-all.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to maven central
        run: ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
